// <auto-generated />
using System;
using EmployeeVoting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EmployeeVoting.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230802211735_added primary keys to dbcontext")]
    partial class addedprimarykeystodbcontext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeVoting.Models.Address", b =>
                {
                    b.Property<int>("address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("address_id"));

                    b.Property<string>("address_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("employee_id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("address_id");

                    b.ToTable("ev_Addresses");
                });

            modelBuilder.Entity("EmployeeVoting.Models.Contact", b =>
                {
                    b.Property<int>("contact_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contact_id"));

                    b.Property<string>("employee_contact")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<int>("employee_id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("contact_id");

                    b.ToTable("ev_Contacts");
                });

            modelBuilder.Entity("EmployeeVoting.Models.Department", b =>
                {
                    b.Property<int>("department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("department_id"));

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("department_id");

                    b.ToTable("ev_Departments");
                });

            modelBuilder.Entity("EmployeeVoting.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<DateTime>("employee_dob")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("employee_email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<int>("role_id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("employee_id");

                    b.ToTable("ev_Employees");
                });

            modelBuilder.Entity("EmployeeVoting.Models.EmployeeHistory", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("history_id"));

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<int>("employee_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("joined_role_date")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("history_id");

                    b.ToTable("ev_EmployeeHistories");
                });

            modelBuilder.Entity("EmployeeVoting.Models.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<int>("department_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("role_id");

                    b.ToTable("ev_Roles");
                });

            modelBuilder.Entity("EmployeeVoting.Models.Vote", b =>
                {
                    b.Property<int>("vote_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vote_id"));

                    b.Property<int>("candidate_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("vote_date")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("voter_id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("vote_id");

                    b.ToTable("ev_Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
